baseURL = 'https://siddsyal.io/'
languageCode = 'en-us'
title = 'Siddharth Syal'
theme = 'hugo-theme-stack'
copyright = 'Siddharth Syal'

# Pagination
[pagination]
    pagerSize = 10

[params]
    mainSections = ['posts']
    featuredImageField = 'image'
    rssFullContent = true
    
    [params.sidebar]
        emoji = 'üë®‚Äçüíª'
        subtitle = 'Security Engineer | Problem Solver | Tech Enthusiast'
        [params.sidebar.avatar]
            enabled = true
            local = true
            src = 'img/avatar.png'
    
    [params.footer]
        since = 2025
        customText = ''
    
    [params.dateFormat]
        published = 'Jan 02, 2006'
        lastUpdated = 'Jan 02, 2006 15:04 MST'
    
    [params.article]
        math = false
        toc = true
        readingTime = true
        [params.article.license]
            enabled = false
            default = 'Licensed under CC BY-NC-SA 4.0'
    
    [params.comments]
        enabled = false
        provider = 'giscus'
    
    [params.colorScheme]
        toggle = true
        default = 'auto'
    
    [params.imageProcessing.cover]
        enabled = true
    [params.imageProcessing.content]
        enabled = true

# Homepage widgets
[[params.widgets.homepage]]
    type = 'search'

[[params.widgets.homepage]]
    type = 'tag-cloud'
    [params.widgets.homepage.params]
        limit = 15

# Social menu
[[menu.social]]
    identifier = 'github'
    name = 'GitHub'
    url = 'https://github.com/siddharthsyal'
    weight = 1
    [menu.social.params]
        icon = 'brand-github'

[[menu.social]]
    identifier = 'linkedin'
    name = 'LinkedIn'
    url = 'https://www.linkedin.com/in/siddharthsyal'
    weight = 2
    [menu.social.params]
        icon = 'linkedin'

# Permalinks
[permalinks]
    posts = '/posts/:slug/'
    page = '/:slug/'

# Output formats
[outputs]
    home = ['HTML', 'RSS']
    page = ['HTML']
    section = ['HTML', 'RSS']

# Markup settings
[markup]
    [markup.goldmark.renderer]
        unsafe = true
    [markup.tableOfContents]
        endLevel = 4
        ordered = true
        startLevel = 2
    [markup.highlight]
        noClasses = false
        codeFences = true
        guessSyntax = true
        lineNos = true
        lineNumbersInTable = true
